<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KROT.Zapret</AssemblyName>
    <RootNamespace>KROT.Zapret</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KROT.Core\KROT.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>

