<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KROT.Diagnostics</AssemblyName>
    <RootNamespace>KROT.Diagnostics</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KROT.Core\KROT.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
